### ISSUE TITLE
Remove 3.x tags (clean up)

### ISSUE THREAD

**Issue by seancoogan** [redhat-cop/openshift-applier#67]
Remove 3.x tags since they have been moved to 2.x

**Comment by oybed** [comment]
@seancoogan thx. The 3.x tags (and releases) actually moved to 1.x in preparation for 2.x, so there's no 2.x equivalent of 3.x. 

Anyway, we're just giving it a bit more time still to make sure everybody have moved off from the 3.x tags before we clean them out.

**Comment by pcarney8** [comment]
@oybed didn't want to lose track of our convo, we mentioned December/New Years to delete these because then it will be ~6 months from the release of `v1.x`

**Comment by InfoSec812** [comment]
I wanted to bring some additional discussion to this based on a convo from RocketChat...

- Many customers are not aware they are even using `openshift-applier`
  - This means that they do not look at our "Announcements"
- We could avoid the problem of deleting the versions by jumping to `4.0` and moving on from there
- Deleting tags/versions seems like it's against what we teach about versioned APIs. We version APIs to ensure that we do not break other people's functionality
- While we're still engaged with a customer, it's relatively easy for us to help them migrate, but after we are no longer on-site a breakage in their playbooks will sow distrust and anger

My suggestion would be bump the version to `4.x` and move on from there.

**Comment by oybed** [comment]
@InfoSec812 thanks for input. At this point in time, the next versions have already been locked in. `v1.x.y` and `v2.x.y` are already in use and will continued to be evolved.

**Comment by oybed** [comment]
@pcarney8 yes, let's plan to do end-of-cy clean-up.

**Comment by darthlukan** [comment]
Since the conversation is happening here, I'll summarize a suggestion from Rocket Chat:
Put a matrix/table in the README that more clearly explains the version scheme. Currently, the only thing in the README related to versions/releases is: `As these repos are under active development, it is strongly recommended to use one of the releases to avoid interruption to your work.`

This of course is incomplete and does not go far enough in addressing @InfoSec812 's point regarding informing the customer, who may very well not even realize the applier is being used (opportunity to adjust training?), but if a customer does chase the rabbit-hole to finding the repo or the README online, they'd at least get the info they're after.

**Comment by pcarney8** [comment]
#89

**Comment by oybed** [comment]
The `v3.x` release/tags have been removed to avoid confusion. Please ensure the correct `v1.x.y` or `v2.x.y` is utilized.
